on: [push]

jobs:
  example:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: neomura/setup-avra-cli-action@v1.0.1
    - run: make
      working-directory: examples
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          example/ntsc.hex
          example/pal-60.hex
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
